### ISSUE TITLE
关于move指令

### ISSUE THREAD

**Issue by ytxytx** [thu-cs-lab/supervisor-la32r#1]
监控程序要求实现move指令，但这个指令在LoongArch 32 Reduced指令集标准中并未提及，在LoongArch Reference Manual中也没有提到。请问这个指令是依据什么使用的呢？同时我也很好奇为什么交叉编译工具链也支持了move指令，可以找到相关说明吗？

**Comment by jiegec** [comment]
move 是伪指令，实际上是 `or rd, rj, zero`
